<?php
/**
 * @file
 * This module allow user with the right permission to generate automatically
 * the embed code of the more reading tracks of a given artist Deezer
 * (name or ID).
 *
 * This module create an new field widget for textarea type :
 *   - First : allow user to choose instance configuration of request option
 * for Deezer api like : layout, color, format ...
 *   - Second : In the add/edit form of an entity, the user can see an new
 * display of textarea field type. The widget add to new action :
 *      - first action : a form with two submit : one to give to the user the
 * possibility to copy and paste the embed code directly in the texterea
 * container. And the second submit give a new form with a textfield and
 * new submit.
 *      - This new form allow user to enter the name or the ID of a Deezer
 * artist. Automatic retrieve the more reading track of this artist. And paste
 * the result in the textarea field container.
 *
 * This module has also a batch action. The user can interact with by two
 * methods : the drush command or the form.
 *
 * All error are save in new table in database and are show in a page to allow
 * user to search why the automatic playlist Deezer does not have result.
 * This table is cleaning by a cron action if administrator choose this option.
 */

module_load_include('inc', 'auto_playlist_deezer', 'auto_playlist_deezer.field');

/**
 * Implements hook_permission().
 */
function auto_playlist_deezer_permission() {
  return array(
    'administer widget playlist deezer' => array(
      'title' => t('Administer widget playlist deezer'),
      'description' => t('Allow users to configure the global iframe parameters'),
    ),
  );
}

/**
 * Implements hook_menu().
 */
function auto_playlist_deezer_menu() {
  $items = array();

  // Deezer settings.
  $items['admin/config/deezer'] = array(
    'title' => 'Deezer',
    'description' => 'General configuration for deezer.',
    'position' => 'right',
    'weight' => 0,
    'page callback' => 'system_admin_menu_block_page',
    'access arguments' => array('access administration pages'),
    'file'  => '/system.admin.inc',
    'file path' => drupal_get_path('module', 'system'),
  );

  $items['admin/config/deezer/widget-playlist'] = array(
    'title' => 'Deezer Widget Playlist',
    'description' => 'General configuration of widget playlist',
    'access arguments' => array('administer widget playlist deezer'),
    'page callback' => 'drupal_get_form',
    'page arguments' => array('auto_playlist_deezer_config_widget_form'),
    'file' => 'auto_playlist_deezer.admin.inc',
  );

  return $items;
}

/**
 * Implements hook_theme().
 */
function auto_playlist_deezer_theme() {
  return array(
    'auto_playlist_deezer_theme_values_element' => array(
      'render element' => 'form',
    ),
    'auto_playlist_deezer_display_iframe' => array(
      'variables' => array('element' => NULL),
    ),
  );
}

/**
 * Action #submit callback : open a form int the widget.
 *
 * The form is show at the bottom of the widget.
 */
function auto_playlist_deezer_open_automatic_form($form, &$form_state) {
  $element = auto_playlist_deezer_ajax_get_element($form, $form_state);
  $apd_id = $element['#apd_id'];

  // Rebuild form widget.
  $form_state['rebuild'] = TRUE;

  $form_state['auto_playlist_deezer'][$apd_id]['form'] = $form_state['triggering_element']['#apd_form'];

}

function auto_playlist_deezer_ajax_get_element($form, $form_state) {
  $element = array();

  $array_parents = $form_state['triggering_element']['#array_parents'];
  // Remove action and action container.
  $array_parents = array_slice($array_parents, 0, -2);

  while (!isset($element['#apd_root'])) {
    $element = drupal_array_get_nested_value($form, $array_parents);
    array_pop($array_parents);
  }

  return $element;
}

/**
 * Implements hook_field_attach_submit().
 */
function auto_playlist_deezer_field_attach_submit($parent_entity_type, $parent_entity, $form, &$form_state) {
  list(, , $bundle_name) = entity_extract_ids($parent_entity_type, $parent_entity);

  foreach (field_info_instances($parent_entity_type, $bundle_name) as $instance_name => $instance) {
    if (isset($instance['widget']) && strpos($instance['widget']['type'], 'inline_form_playlist_deezer') === 0) {
      $field_name = $instance['field_name'];
      if (!isset($form[$field_name])) {
        // The field wasn't found on this form, skip it.
        continue;
      }
      $langcode = $form[$field_name]['#language'];

      // The location of #apd_id for textarea is under the delta value of item.
      // We need to loop on numeric increment to test if we find it.
      $apd_id = '';
      foreach ($form[$field_name][$langcode] as $key => $value) {
        if (is_numeric($key) && is_array($value)) {
          $array_parents = array_merge($form[$field_name][$langcode][$key]['#array_parents'], array('#apd_id'));
          if (!drupal_array_nested_key_exists($form, $array_parents)) {
            continue;
          }
          else {
            $new_apd_id = drupal_array_get_nested_value($form, $array_parents);
            if ($apd_id != $new_apd_id) {
              $apd_id = $new_apd_id;
            }
          }
        }
      }

      if (empty($apd_id)) {
        // The field is present on the form, but the Auto Playlist Deezer
        // widget wasn't added.
        continue;
      }

      if (empty($form_state['auto_playlist_deezer'][$apd_id])) {
        // No data found, no need to do anything.
        continue;
      }

      $values = $form_state['auto_playlist_deezer'][$apd_id];

      // Respect the entity weights.
      // uasort($values['entities'], 'drupal_sort_weight');
      // Go through the IEF data and assemble a list of ids.
      $field_values = array();
      foreach ($values['values'] as $item) {
        $field_values[] = $item;
      }

      if (!empty($field_values)) {
        // Set the list of ids as the field value.
        $parent_entity->{$field_name}[$langcode] = $field_values;
      }
    }
  }
}

function auto_playlist_deezer_manually_form($element_form, &$form_state, $default_value = NULL) {
  $settings = $form_state['auto_playlist_deezer'][$element_form['#apd_id']]['settings'];
  $settings_embed_config = $settings['auto_playlist_deezer']['embed_configuration'];
  $delta = $element_form['#apd_id'];

  if ($element_form['#op'] == 'add') {
    $element_form['#title'] = t('Manually generate the embed deezer code.');
    $element_form['#description'] = t('Choose all options to personalize the player to embed.');
    $submit_value = t('Create embed Deezer');
  }
  elseif ($element_form['#op'] == 'manual_edit') {
    $element_form['#title'] = t('Update the embed deezer code.');
    $delta .= '-' . $element_form['#apd_row_delta'];
    $element_form['#description'] = t('Choose all options to personalize the player to embed.');
    $submit_value = t('Update embed Deezer');
  }

  if (!empty($default_value)) {
    $settings_embed_config = auto_playlist_extract_embed_config($default_value);
  }

  auto_playlist_deezer_config_iframe_form($element_form, $settings_embed_config);

  // Form action part.
  $element_form['actions'] = array(
    '#type' => 'container',
    '#weight' => 50,
  );

  $element_form['actions']['apd_' . $element_form['#op'] . '_save'] = array(
    '#type' => 'submit',
    '#value' => $submit_value,
    '#name' => 'apd-' . $element_form['#op'] . '-submit-' . $delta,
    '#limit_validation_errors' => array($element_form['#parents']),
    '#attributes' => array('class' => array('apd-manually-submit')),
    '#ajax' => array(
      'callback' => 'auto_playlist_deezer_ajax_get_element',
      'wrapper' => 'automatic-playlist-deezer-' . $element_form['#apd_id'],
    ),
  );
  $element_form['actions']['apd_' . $element_form['#op'] . '_cancel'] = array(
    '#type' => 'submit',
    '#value' => t('Cancel'),
    '#name' => 'apd-' . $element_form['#op'] . '-cancel-' . $delta,
    '#limit_validation_errors' => array(),
    '#attributes' => array('class' => array('apd-manually-cancel')),
    '#ajax' => array(
      'callback' => 'auto_playlist_deezer_ajax_get_element',
      'wrapper' => 'automatic-playlist-deezer-' . $element_form['#apd_id'],
    ),
  );

  if ($element_form['#op'] == 'add') {
    $element_form['actions']['apd_add_save']['#submit'] = array(
      'auto_playlist_deezer_trigger_submit',
      'auto_playlist_deezer_close_child_forms',
      'auto_playlist_deezer_close_form',
    );
    $element_form['actions']['apd_add_cancel']['#submit'] = array(
      'auto_playlist_deezer_close_child_forms',
      'auto_playlist_deezer_close_form',
    );
  }
  elseif ($element_form['#op'] == 'manual_edit') {
    $element_form['actions']['apd_manual_edit_save']['#apd_row_delta'] = $element_form['#apd_row_delta'];
    $element_form['actions']['apd_manual_edit_cancel']['#apd_row_delta'] = $element_form['#apd_row_delta'];

    $element_form['actions']['apd_manual_edit_save']['#submit'] = array(
      'auto_playlist_deezer_trigger_submit',
      'auto_playlist_deezer_close_child_forms',
      'auto_playlist_deezer_close_row_form',
    );
    $element_form['actions']['apd_manual_edit_cancel']['#submit'] = array(
      'auto_playlist_deezer_close_child_forms',
      'auto_playlist_deezer_close_row_form',
    );
  }

  $element_form['#apd_element_submit'][] = 'auto_playlist_deezer_manually_form_submit';
  $element_form['#pre_render'][] = 'auto_display_deezer_pre_render_fieldset_markup';

  return $element_form;
}

function auto_playlist_deezer_close_form($form, &$form_state) {
  $element = auto_playlist_deezer_ajax_get_element($form, $form_state);
  $apd_id = $element['#apd_id'];

  $form_state['rebuild'] = TRUE;
  $form_state['auto_playlist_deezer'][$apd_id]['form'] = NULL;
}

function auto_playlist_deezer_manually_form_submit($element_form, &$form_state) {
  $apd_id = $element_form['#apd_id'];
  $instance = $form_state['auto_playlist_deezer'][$apd_id]['instance'];
  $field_name = $instance['field_name'];

  if ($element_form['#op'] == 'add') {
    $delta = 0;
    if (!empty($form_state['auto_playlist_deezer'][$apd_id]['values'])) {
      $delta = max(array_keys($form_state['auto_playlist_deezer'][$apd_id]['values'])) + 1;
    }
    $form_state['auto_playlist_deezer'][$apd_id]['values'][] = array(
      'value' => $form_state['values'][$field_name]['und']['form']['field_text_value'],
      'format' => NULL,
      'weight' => $delta,
    );
  }
  else {
    $delta = $element_form['#apd_row_delta'];
    $form_state['auto_playlist_deezer'][$apd_id]['values'][$delta]['value'] = $form_state['values'][$field_name]['und']['values'][$delta]['form']['field_text_value'];
  }
}

function auto_playlist_deezer_config_iframe_form(&$element, $settings = array()) {
  // Deezer configuration type. By default tracks.
  $element['auto_playlist_deezer']['embed_configuration']['type'] = array(
    '#type' => 'select',
    '#title' => t('The type of music you want to play'),
    '#default_value' => isset($settings['type']) ? $settings['type'] : '',
    '#options' => auto_playlist_deezer_get_type(),
  );

  // Deezer configuration iframe width. By default 600px.
  $element['auto_playlist_deezer']['embed_configuration']['width'] = array(
    '#type' => 'textfield',
    '#size' => 4,
    '#maxlength' => 4,
    '#title' => t('	The width of the widget.'),
    '#default_value' => isset($settings['width']) ? $settings['width'] : '',
    '#element_validate' => array('element_validate_integer_positive'),
  );

  // Deezer configuration iframe height. By default 200px.
  $element['auto_playlist_deezer']['embed_configuration']['height'] = array(
    '#type' => 'textfield',
    '#size' => 4,
    '#maxlength' => 4,
    '#title' => t('The height of the widget.'),
    '#default_value' => isset($settings['height']) ? $settings['height'] : '',
    '#element_validate' => array('element_validate_integer_positive'),
  );

  // Deezer configuration layout. By default dark.
  $element['auto_playlist_deezer']['embed_configuration']['layout'] = array(
    '#type' => 'select',
    '#title' => t('The general layout of the widget'),
    '#default_value' => isset($settings['layout']) ? $settings['layout'] : '',
    '#options' => array(
      'dark' => t('Dark'),
      'light' => t('Light'),
    ),
  );

  // Deezer configuration display playlist. By default FALSE.
  $element['auto_playlist_deezer']['embed_configuration']['playlist'] = array(
    '#type' => 'checkbox',
    '#title' => t('Display the playlist or not'),
    '#default_value' => isset($settings['playlist']) ? $settings['playlist'] : '',
  );

  // Deezer configuration autoplay. By default FALSE.
  $element['auto_playlist_deezer']['embed_configuration']['autoplay'] = array(
    '#type' => 'checkbox',
    '#title' => t('Plays automatically the music after loading.'),
    '#default_value' => isset($settings['autoplay']) ? $settings['autoplay'] : '',
  );

  // Deezer configuration format. By default classic.
  $element['auto_playlist_deezer']['embed_configuration']['format'] = array(
    '#prefix' => '<div class="auto-playlist-deezer-format-wrapper">',
    '#suffix' => '</div>',
    '#type' => 'select',
    '#title' => t('The layout format of the widget'),
    '#default_value' => isset($settings['format']) ? $settings['format'] : '',
    '#options' => array(
      'square' => t('Square'),
      'classic' => t('Classic'),
    ),
    '#attached' => array(
      'js' =>array(
        drupal_get_path('module', 'auto_playlist_deezer') . '/js/auto_plylist_deezer.js',
      ),
    ),
  );

  // Deezer configuration size. By default medium.
  $element['auto_playlist_deezer']['embed_configuration']['size'] = array(
    '#prefix' => '<div class="auto-playlist-deezer-size-wrapper">',
    '#suffix' => '</div>',
    '#type' => 'select',
    '#title' => t('The layout size of the widget'),
    '#default_value' => isset($settings['size']) ? $settings['size'] : '',
    '#options' => array(
      'small' => t('Small'),
      'medium' => t('Medium'),
      'big' => t('Big'),
    ),
  );

  // Deezer configuration color. By default 007FEB.
  $element['auto_playlist_deezer']['embed_configuration']['color'] = array(
    '#type' => 'textfield',
    '#size' => 6,
    '#maxlength' => 6,
    '#title' => t('The general color of the widget. Has to be a hexadecimal value without the #'),
    '#default_value' => isset($settings['color']) ? $settings['color'] : '',
  );
}

/**
 * Implements hook_form_alter().
 */
function auto_playlist_deezer_form_alter(&$form, &$form_state, $form_id) {
  if (!empty($form_state['auto_display_deezer'])) {
    $element_submit = NULL;
    if (!empty($form['submit'])) {
      $element_submit = &$form['submit'];
    }
    elseif (!empty($form['actions']['submit'])) {
      $element_submit = &$form['actions']['submit'];
    }

    if ($element_submit) {
      $submit = array_merge(array('auto_playlist_deezer_trigger_submit'), $form['#submit']);
      if (!empty($element_submit['#submit'])) {
        $submit = array_merge($submit, $element_submit['#submit']);
        $element_submit['#submit'] = array_unique($submit);
      }
      else {
        $element_submit['#submit'] = $submit;
      }
      $element_submit['#apd_submit_all'] = TRUE;
    }
  }
}

function auto_playlist_deezer_trigger_submit($form, &$form_state) {
  if (!empty($form_state['triggering_element']['#apd_submit_all'])) {
    auto_playlist_deezer_form_submit($form, $form_state);
  }
  else {
    $array_parents = $form_state['triggering_element']['#array_parents'];
    $array_parents = array_slice($array_parents, 0, -2);
    $element = drupal_array_get_nested_value($form, $array_parents);
    auto_playlist_deezer_form_submit($element, $form_state);
  }
}

function auto_playlist_deezer_form_submit($element, &$form_state) {
  foreach (element_children($element) as $key) {
    if (!empty($element[$key])) {
      auto_playlist_deezer_form_submit($element[$key], $form_state);
    }
  }

  if (!empty($element['#apd_element_submit'])) {
    foreach ($element['#apd_element_submit'] as $function) {
      $function($element, $form_state);
    }
  }
}

/**
 * Callback : submit for row element item.
 */
function auto_playlist_deezer_open_row_element($form, &$form_state) {
  $element = auto_playlist_deezer_ajax_get_element($form, $form_state);
  $apd_id = $element['#apd_id'];
  $delta = $form_state['triggering_element']['#apd_row_delta'];

  $form_state['rebuild'] = TRUE;
  $form_state['auto_playlist_deezer'][$apd_id]['values'][$delta]['form'] = $form_state['triggering_element']['#apd_row_form'];
}

/**
 * Theme : return the HTML form of value(s) in field using auto playlist
 * deezer field widget.
 */
function theme_auto_playlist_deezer_theme_values_element($vars) {
  $header = array();
  $rows = array();

  $form = $vars['form'];
  $has_tabledrag = TRUE;

  foreach(element_children($form) as $key) {
    if (!empty($form[$key]['form'])) {
      $has_tabledrag = FALSE;
    }
  }

  if ($has_tabledrag) {
    $header[] = array('data' => '', 'class' => array('apd-tabledrag-header'));
    $header[] = array('data' => t('Sort order'), 'class' => array('apd-sort-order-header'));
  }

  $header[] = t('Value');
  $header[] = t('Operation');

  foreach (element_children($form) as $key) {
    $row_classes = array('apd-row-value');
    $cells = array();
    if ($has_tabledrag) {
      $cells[] = array('data' => '', 'class' => array('apd-tabledrag-handle'));
      $cells[] = drupal_render($form[$key]['delta']);
      $row_classes[] = 'draggable';
    }
    $cells[] = array(
      'data' => $form[$key]['#info_value'],
    );

    $cells[] = array(
      'data' => drupal_render($form[$key]['actions']),
    );

    $rows[] = array('data' => $cells, 'class' => $row_classes);

    if (!empty($form[$key]['form'])) {
      $row = array(
        array(
          'data' => drupal_render($form[$key]['form']),
          'colspan' => 3,
        ),
      );
      $rows[] = array(
        'data' => $row,
        'class' => array('apd-row-form'),
        'no_striping' => TRUE,
      );
    }
  }

  if (!empty($rows)) {
    $id = 'apd-value-table-' . $form['#id'];
    if ($has_tabledrag) {
      drupal_add_tabledrag($id, 'order', 'sibling', 'apd-values-delta');
    }

    $table_attributes = array(
      'id' => $id,
      'class' => array('apd-values-table'),
    );

    // Return table theme of the list items.
    return theme('table', array(
      'header' => $header,
      'rows' => $rows,
      'sticky' => FALSE,
      'attributes' => $table_attributes,
    ));
  }
}

/**
 * Theme for field content embed deezer.
 */
function theme_auto_playlist_deezer_display_iframe($element) {
  $output = '';

  if (!empty($element['element'])) {
    $output .= $element['element'];
  }

  return $output;
}

function auto_playlist_deezer_close_child_forms($form, &$form_state) {
  $element = auto_playlist_deezer_ajax_get_element($form, $form_state);
  foreach (element_children($element) as $key) {
    if (!empty($element[$key])) {
      auto_playlist_deezer_close_all_forms($element[$key], $form_state);
    }
  }
}

function auto_playlist_deezer_close_all_forms($elements, &$form_state) {
  foreach (element_children($elements) as $key) {
    if (!empty($elements[$key])) {
      auto_playlist_deezer_close_all_forms($elements[$key], $form_state);
    }
  }

  if (!empty($elements['#apd_id'])) {
    $apd_id = $elements['#apd_id'];
    $form_state['auto_playlist_deezer'][$apd_id]['form'] = NULL;

    foreach ($form_state['auto_playlist_deezer'][$apd_id]['values'] as &$value) {
      $value['form'] = NULL;
    }
  }
}

function auto_display_deezer_pre_render_fieldset_markup($form) {
  $sort = array();
  foreach (element_children($form) as $key) {
    $element = $form[$key];
    if (isset($element['#fieldset']) && isset($form[$element['#fieldset']])) {
      $form[$element['#fieldset']][$key] = $element;
      unset($form[$key]);
      if (!in_array($key, $sort)) {
        $sort[] = $element['#fieldset'];
      }
    }
  }
  foreach ($sort as $key) {
    uasort($form[$key], 'element_sort');
  }

  return $form;
}

function auto_playlist_deezer_close_row_form($form, &$form_state) {
  $element = auto_playlist_deezer_ajax_get_element($form, $form_state);
  $apd_id = $element['#apd_id'];
  $delta = $form_state['triggering_element']['#apd_row_delta'];

  $form_state['rebuild'] = TRUE;
  $form_state['auto_playlist_deezer'][$apd_id]['values'][$delta]['form'] = NULL;
}

/**
 *
 */
function auto_playlist_deezer_remove_form($form_element, $form_state) {
  $delta = $form_element['#apd_id'] . '-' . $form_element['#apd_row_delta'];

  // Create the form.
  $form_element['message'] = array(
    '#markup' => '<div>' . t('Are you sure you want to remove this content. This action is irreversible.'),
  );

  // Add action part.
  $form_element['actions'] = array(
    '#type' => 'container',
    '#weight' => 50,
  );

  $form_element['actions']['apd_remove_confirm'] = array(
    '#type' => 'submit',
    '#value' => t('Remove'),
    '#name' => 'apd-remove-confirm-' . $delta,
    '#limit_validation_errors' => array($form_element['#parents']),
    '#ajax' => array(
      'callback' => 'auto_playlist_deezer_ajax_get_element',
      'wrapper' => 'automatic-playlist-deezer-' . $form_element['#apd_id'],
    ),
    '#submit' => array('auto_playlist_deezer_remove_confirm'),
    '#apd_row_delta' => $form_element['#apd_row_delta']
  );
  $form_element['actions']['apd_remove_cancel'] = array(
    '#type' => 'submit',
    '#value' => t('Cancel'),
    '#name' => 'apd-remove-cancel-' . $delta,
    '#limit_validation_errors' => array(),
    '#ajax' => array(
      'callback' => 'auto_playlist_deezer_ajax_get_element',
      'wrapper' => 'automatic-playlist-deezer-' . $form_element['#apd_id'],
    ),
    '#submit' => array('auto_playlist_deezer_close_row_form'),
    '#apd_row_delta' => $form_element['#apd_row_delta']
  );

  return $form_element;
}

function auto_playlist_deezer_remove_confirm($form, &$form_state) {
  $form_state['rebuild'] = TRUE;
  $element = auto_playlist_deezer_ajax_get_element($form, $form_state);
  $apd_id = $element['#apd_id'];
  $delta = $form_state['triggering_element']['#apd_row_delta'];

  unset($form_state['auto_playlist_deezer'][$apd_id]['values'][$delta]);
}

/**
 *
 */
function auto_playlist_deezer_automatic_form($element_form, $form_state) {
  $settings = $form_state['auto_playlist_deezer'][$element_form['#apd_id']]['settings'];
  $delta = $element_form['#apd_id'];
  $element_form['#description'] = t('Enter the Name or ID to generate the embed deezer code.');

  if ($element_form['#op'] == 'add') {
    $element_form['#title'] = t('Generate the embed deezer code.');
    $submit_value = t('Generate embed Deezer');
  }
  elseif ($element_form['#op'] == 'automatic_edit') {
    $element_form['#title'] = t('Update the embed deezer code.');
    $delta .= '-' . $element_form['#apd_row_delta'];
    $submit_value = t('Update embed Deezer');
  }

  $element_form['field_name_id'] = array(
    '#title' => $element_form['#title'],
    '#description' => $element_form['#description'],
    '#type' => 'textfield',
    '#rows' => $settings['rows'],
    '#required' => TRUE,
    '#attributes' => array('class' => array('textfield')),
  );

  // Form action part.
  $element_form['actions'] = array(
    '#type' => 'container',
    '#weight' => 50,
  );

  $element_form['actions']['apd_' . $element_form['#op'] . '_save'] = array(
    '#type' => 'submit',
    '#value' => $submit_value,
    '#name' => 'apd-' . $element_form['#op'] . '-submit-' . $delta,
    '#limit_validation_errors' => array($element_form['#parents']),
    '#attributes' => array('class' => array('apd-automatic-submit')),
    '#ajax' => array(
      'callback' => 'auto_playlist_deezer_ajax_get_element',
      'wrapper' => 'automatic-playlist-deezer-' . $element_form['#apd_id'],
    ),
  );
  $element_form['actions']['apd_' . $element_form['#op'] . '_cancel'] = array(
    '#type' => 'submit',
    '#value' => t('Cancel'),
    '#name' => 'apd-' . $element_form['#op'] . '-cancel-' . $delta,
    '#limit_validation_errors' => array(),
    '#attributes' => array('class' => array('apd-automatic-cancel')),
    '#ajax' => array(
      'callback' => 'auto_playlist_deezer_ajax_get_element',
      'wrapper' => 'automatic-playlist-deezer-' . $element_form['#apd_id'],
    ),
  );

  if ($element_form['#op'] == 'add') {
    $element_form['actions']['apd_add_save']['#submit'] = array(
      'auto_playlist_deezer_trigger_submit',
      'auto_playlist_deezer_close_child_forms',
      'auto_playlist_deezer_close_form',
    );
    $element_form['actions']['apd_add_cancel']['#submit'] = array(
      'auto_playlist_deezer_close_child_forms',
      'auto_playlist_deezer_close_form',
    );
  }
  elseif ($element_form['#op'] == 'automatic_edit') {
    $element_form['actions']['apd_automatic_edit_save']['#apd_row_delta'] = $element_form['#apd_row_delta'];
    $element_form['actions']['apd_automatic_edit_cancel']['#apd_row_delta'] = $element_form['#apd_row_delta'];

    $element_form['actions']['apd_automatic_edit_save']['#submit'] = array(
      'auto_playlist_deezer_trigger_submit',
      'auto_playlist_deezer_close_child_forms',
      'auto_playlist_deezer_close_row_form',
    );
    $element_form['actions']['apd_automatic_edit_cancel']['#submit'] = array(
      'auto_playlist_deezer_close_child_forms',
      'auto_playlist_deezer_close_row_form',
    );
  }

  $element_form['#apd_element_submit'][] = 'auto_playlist_deezer_automatic_form_submit';
  $element_form['#pre_render'][] = 'auto_display_deezer_pre_render_fieldset_markup';

  return $element_form;
}


function auto_playlist_deezer_automatic_form_submit($element_form, &$form_state) {
  $apd_id = $element_form['#apd_id'];
  $settings = $form_state['auto_playlist_deezer'][$apd_id]['settings'];
  $instance = $form_state['auto_playlist_deezer'][$apd_id]['instance'];
  $field_name = $instance['field_name'];

  if ($element_form['#op'] == 'add') {
    $field_value = $form_state['values'][$field_name]['und']['form']['field_name_id'];
    $delta = 0;

    if (!empty($form_state['auto_playlist_deezer'][$apd_id]['values'])) {
      $delta = max(array_keys($form_state['auto_playlist_deezer'][$apd_id]['values'])) + 1;
    }

    $embed_deezer = auto_playlist_deezer_get_deezer_value($field_value, $settings);
    if (!empty($embed_deezer)) {
      $form_state['auto_playlist_deezer'][$apd_id]['values'][] = array(
        'value' => $embed_deezer,
        'format' => NULL,
        'weight' => $delta,
      );
    }
    else {
      // @TODO return message to say that we can't save an empty value.
      // @TODO form_set_error or just a error message ?
    }
  }
  else {
    $delta = $element_form['#apd_row_delta'];
    $field_value = $form_state['values'][$field_name]['und']['values'][$delta]['form']['field_name_id'];
    $embed_deezer = auto_playlist_deezer_get_deezer_value($field_value, $settings);

    if (!empty($embed_deezer)) {
      $form_state['auto_playlist_deezer'][$apd_id]['values'][$delta]['value'] = $embed_deezer;
    }
  }
}

function auto_playlist_deezer_get_deezer_value($value, $settings) {
  module_load_include('php', 'auto_playlist_deezer', 'includes/AutoPlaylistDeezer');

  $proxy_config = array(
    'proxy_server' => variable_get('proxy_server', ''),
    'proxy_port' => variable_get('proxy_port', 8080),
    'proxy_username' => variable_get('proxy_username', ''),
    'proxy_password' => variable_get('proxy_password', ''),
    'proxy_user_agent' => variable_get('proxy_user_agent', ''),
  );

  $deezer_embed_settings = $settings['auto_playlist_deezer']['embed_configuration'];
  $deezer_track_settings = $settings['auto_playlist_deezer']['tracks_configuration'];

  $embed_deezer = new AutoPlaylistDeezer($deezer_embed_settings, $deezer_track_settings, $proxy_config);

  // First we need to check if the data is a string or int.
  if (is_numeric($value)) {
    $embed_deezer->getTopTracksListByArtistId($value);
  }
  elseif (is_string($value)) {
    $embed_deezer->getTopTracksListByArtistName($value);
  }
  else {
    // @TODO set an error message that say the data to search is not an numeric or string type.
  }

  return $embed_deezer->iframe;
}

/**
 * Helper : return the list of deezer music type for select list options.
 */
function auto_playlist_deezer_get_type() {
  return array(
    'playlist' => t('Playlist'),
    'album' => t('Album'),
    'tracks' => t('Tracks'),
    'podcast' => t('Podcast'),
    'episodes' => t('Episodes'),
    'radio' => t('Mix'),
    'charts' => t('Charts'),
  );
}

/**
 * Helper : Extract all configuration of the iframe.
 */
function auto_playlist_extract_embed_config($value) {
  $settings = array();

  if (!empty($value)) {
    if (preg_match('/src="(.*?)"/', $value, $matches)) {
      if (!empty($matches[1])) {
        $url_parsed = drupal_parse_url($matches[1]);
        if (!empty($url_parsed['query'])) {
          $settings = $url_parsed['query'];
        }
      }
    }
  }

  return $settings;
}
